apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::815112297653:role/MainStack-k8WorkerNodes-GZ471C1AE-NodeInstanceRole-1QXOVWOR4LO27
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::815112297653:user/SuperUser
      username: SuperUser
metadata: 
  name: aws-auth
  namespace: kube-system
kind: ConfigMap
