apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::815112297653:instance-profile/eks-6ac586a5-b329-89be-91c3-63fe4f8365e8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::815112297653:user/SuperUser
      username: SuperUser
metadata: 
  name: aws-auth
  namespace: kube-system
kind: ConfigMap
